class Commands:
    LEECH = "leech@DPLeech_Bot"
    PURGE = "purge@DPLeech_Bot"
    PAUSEALL = "pauseall@DPLeech_Bot"
    RESUMEALL = "resumeall@DPLeech_Bot"
    STATUS = "status@DPLeech_Bot"
    SETTINGS = "settings@DPLeech_Bot"
    EXEC = "exec@DPLeech_Bot"
    UPLOAD = "upload@DPLeech_Bot"
    YTDL = "ytdl@DPLeech_Bot"
    PYTDL = "pytdl@DPLeech_Bot"
    ABOUT = "about@DPLeech_Bot"
    GETLOGS = "getlogs@DPLeech_Bot"
    SERVER = "server@DPLeech_Bot"
    USERSETTINGS = "usetting@DPLeech_Bot"
    INSTADL = "instadl@DPLeech_Bot"
